import AppKit
import Foundation
import ImageIO
import UniformTypeIdentifiers

@MainActor
final class PasteboardCodec {
    enum CodecError: LocalizedError {
        case emptyPasteboard
        case concealedContent
        case unsupportedContent
        case representationTooLarge(String)
        case writeFailed

        var errorDescription: String? {
            switch self {
            case .emptyPasteboard:
                "The clipboard is empty."
            case .concealedContent:
                "Protected or transient clipboard content was ignored."
            case .unsupportedContent:
                "This clipboard content has no supported representations."
            case let .representationTooLarge(type):
                "The \(type) representation is too large to store."
            case .writeFailed:
                "Passst could not write the selection to the clipboard."
            }
        }
    }

    private let maximumRepresentationSize = 128 * 1_024 * 1_024
    private let ignoredTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.agilebits.onepassword.private",
        "com.1password.1password"
    ]

    func capture(from pasteboard: NSPasteboard = .general) throws -> ClipboardPayload {
        guard let pasteboardItems = pasteboard.pasteboardItems, !pasteboardItems.isEmpty else {
            throw CodecError.emptyPasteboard
        }

        if pasteboardItems.contains(where: { item in
            item.types.contains { ignoredTypes.contains($0.rawValue) }
        }) {
            throw CodecError.concealedContent
        }

        var payloadItems: [ClipboardPayloadItem] = []
        var plainTextParts: [String] = []
        var fileURLs: [URL] = []

        for pasteboardItem in pasteboardItems {
            var representations: [PasteboardRepresentation] = []
            for type in pasteboardItem.types where !ignoredTypes.contains(type.rawValue) {
                guard let data = pasteboardItem.data(forType: type) else { continue }
                guard data.count <= maximumRepresentationSize else {
                    throw CodecError.representationTooLarge(type.rawValue)
                }
                representations.append(PasteboardRepresentation(type: type, data: data))
            }

            if let value = pasteboardItem.string(forType: .string), !value.isEmpty {
                plainTextParts.append(value)
                if !representations.contains(where: {
                    $0.typeIdentifier == NSPasteboard.PasteboardType.string.rawValue
                }), let data = value.data(using: .utf8) {
                    representations.append(PasteboardRepresentation(type: .string, data: data))
                }
            }

            if let fileURLString = pasteboardItem.string(forType: .fileURL),
               let url = URL(string: fileURLString) {
                fileURLs.append(url)
            }

            representations = ImageRepresentationNormalizer
                .addingPortablePNGIfNeeded(to: representations)

            if !representations.isEmpty {
                payloadItems.append(ClipboardPayloadItem(representations: representations))
            }
        }

        guard !payloadItems.isEmpty else {
            throw CodecError.unsupportedContent
        }

        return ClipboardPayload(
            items: payloadItems,
            plainText: plainTextParts.isEmpty ? nil : plainTextParts.joined(separator: "\n"),
            fileURLs: fileURLs
        )
    }

    @discardableResult
    func write(
        _ payload: ClipboardPayload,
        to pasteboard: NSPasteboard = .general
    ) throws -> Int {
        pasteboard.clearContents()

        let items = payload.items.compactMap { payloadItem -> NSPasteboardItem? in
            let item = NSPasteboardItem()
            var didWrite = false
            for representation in payloadItem.representations {
                if representation.pasteboardType == .string,
                   let value = String(data: representation.data, encoding: .utf8) {
                    didWrite = item.setString(value, forType: .string) || didWrite
                } else {
                    didWrite = item.setData(
                        representation.data,
                        forType: representation.pasteboardType
                    ) || didWrite
                }
            }
            return didWrite ? item : nil
        }

        guard !items.isEmpty, pasteboard.writeObjects(items) else {
            throw CodecError.writeFailed
        }
        return pasteboard.changeCount
    }
}

enum ClipboardPayloadClassifier {
    static func kind(for payload: ClipboardPayload) -> ClipboardContentKind {
        let representations = payload.items.flatMap(\.representations)
        let types = Set(representations.map(\.typeIdentifier))

        let hasFiles = types.contains(NSPasteboard.PasteboardType.fileURL.rawValue)
            || !payload.fileURLs.isEmpty
        let hasImage = representations.contains { representation in
            UTType(representation.typeIdentifier)?.conforms(to: .image) == true
        }
        let hasRichText = types.contains(NSPasteboard.PasteboardType.rtf.rawValue)
            || types.contains(NSPasteboard.PasteboardType.html.rawValue)
        let text = payload.plainText?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""

        if hasImage {
            let containsNonImageFile = payload.fileURLs.contains { url in
                guard !url.pathExtension.isEmpty,
                      let type = UTType(filenameExtension: url.pathExtension)
                else {
                    return true
                }
                return !type.conforms(to: .image)
            }
            return containsNonImageFile ? .mixed : .image
        }
        if hasFiles { return .files }
        if looksLikeColor(text) { return .color }
        if looksLikeURL(text) { return .link }
        if CodeDetector.isLikelyCode(text) { return .code }
        if hasRichText { return .richText }
        return .text
    }

    static func makeRecord(
        for payload: ClipboardPayload,
        sourceApplication: NSRunningApplication?
    ) -> ClipboardRecord {
        makeRecord(
            for: payload,
            sourceBundleIdentifier: sourceApplication?.bundleIdentifier,
            sourceApplicationName: sourceApplication?.localizedName
        )
    }

    static func makeRecord(
        for payload: ClipboardPayload,
        sourceBundleIdentifier: String?,
        sourceApplicationName: String?
    ) -> ClipboardRecord {
        let kind = kind(for: payload)
        let plainText = payload.plainText?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        let fileNames = payload.fileURLs.map(\.lastPathComponent)
        let title: String
        let preview: String

        switch kind {
        case .files:
            if let first = fileNames.first, fileNames.count > 1 {
                title = "\(first) +\(fileNames.count - 1)"
            } else {
                title = fileNames.first ?? "Files"
            }
            preview = fileNames.joined(separator: "\n")
        case .image:
            title = fileNames.first
                ?? imageFilenameCandidate(from: plainText)
                ?? "Image"
            preview = imageDimensions(payload).map { "\($0.width) × \($0.height)" } ?? ""
        case .link:
            title = URL(string: plainText)?.host() ?? "Link"
            preview = plainText
        case .color:
            title = plainText.uppercased()
            preview = plainText
        case .richText:
            title = firstMeaningfulLine(plainText, fallback: "Formatted text")
            preview = plainText
        case .code:
            title = firstMeaningfulLine(plainText, fallback: "Code")
            preview = plainText
        case .mixed:
            title = firstMeaningfulLine(plainText, fallback: "Mixed content")
            preview = plainText.isEmpty ? fileNames.joined(separator: "\n") : plainText
        case .text:
            title = firstMeaningfulLine(plainText, fallback: "Text")
            preview = plainText
        }

        let searchable = [
            plainText,
            fileNames.joined(separator: " "),
            payload.fileURLs.map(\.path).joined(separator: " "),
            sourceApplicationName ?? ""
        ]
            .filter { !$0.isEmpty }
            .joined(separator: "\n")

        return ClipboardRecord(
            kind: kind,
            displayTitle: String(title.prefix(180)),
            previewText: String(preview.prefix(12_000)),
            searchableText: searchable,
            sourceBundleIdentifier: sourceBundleIdentifier,
            sourceApplicationName: sourceApplicationName,
            payloadFilename: "",
            thumbnailFilename: nil,
            payloadDigest: payload.stableDigest,
            byteCount: payload.byteCount
        )
    }

    private static func firstMeaningfulLine(_ text: String, fallback: String) -> String {
        text
            .split(whereSeparator: \.isNewline)
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .first(where: { !$0.isEmpty })
            .map { String($0) } ?? fallback
    }

    private static func imageFilenameCandidate(from text: String) -> String? {
        let candidate = text
            .split(whereSeparator: \.isNewline)
            .first
            .map(String.init)?
            .trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        guard !candidate.isEmpty else { return nil }
        let name = URL(string: candidate)?.lastPathComponent.isEmpty == false
            ? URL(string: candidate)?.lastPathComponent
            : URL(fileURLWithPath: candidate).lastPathComponent
        guard let name, !name.isEmpty,
              let type = UTType(filenameExtension: URL(fileURLWithPath: name).pathExtension),
              type.conforms(to: .image)
        else {
            return nil
        }
        return name
    }

    private static func looksLikeURL(_ text: String) -> Bool {
        guard let url = URL(string: text),
              let scheme = url.scheme?.lowercased()
        else {
            return false
        }
        return ["http", "https", "ftp", "mailto"].contains(scheme)
    }

    private static func looksLikeColor(_ text: String) -> Bool {
        let value = text.trimmingCharacters(in: .whitespacesAndNewlines)
        let pattern = #"^#(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$"#
        return value.range(of: pattern, options: .regularExpression) != nil
    }

    private static func imageDimensions(_ payload: ClipboardPayload) -> (width: Int, height: Int)? {
        guard let data = payload.preferredImageData,
              let source = CGImageSourceCreateWithData(data as CFData, nil),
              let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil)
                as? [CFString: Any],
              let width = properties[kCGImagePropertyPixelWidth] as? Int,
              let height = properties[kCGImagePropertyPixelHeight] as? Int
        else {
            return nil
        }
        return (width, height)
    }
}
